# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy TeamBuilder.GitHub & TeamBuilder.Serverless

on:
  push:
    branches:
      - main
    paths:
      - '.github\workflows\GitHubApi.yml'
      - 'TeamBuilder.GitHub/**'
      - 'TeamBuilder.Serverless/**'
      - 'templates/**'
      - 'TeamBuilder.Models/**'
  workflow_dispatch:

env:
  BUILDCONFIGURATION: 'Release'
  AZURE_SUBSCRIPTION_ID: 'da454a5b-6be8-4084-8841-b913918f9aa6'
  AZURE_RESOURCE_GROUP: 'hackathonTeamBuilder-36mph-rg'

jobs:
  build:
    name: Build - TeamBuilder.GitHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Build API
      run: dotnet build ./TeamBuilder.GitHub --configuration ${{env.BUILDCONFIGURATION}}

    - name: Build Serverless
      run: dotnet build ./TeamBuilder.Serverless --configuration ${{env.BUILDCONFIGURATION}}

    - name: create API artifact
      run: dotnet publish ./TeamBuilder.GitHub -c ${{env.BUILDCONFIGURATION}} -o ${{env.DOTNET_ROOT}}/myapp

    - name: create Serverless artifact
      run: dotnet publish ./TeamBuilder.Serverless -c ${{env.BUILDCONFIGURATION}} -o ${{env.DOTNET_ROOT}}/functions

    - name: Upload API artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

    - name: Upload Serverless artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: func-app
        path: ${{env.DOTNET_ROOT}}/functions

  provision:
    name: Provision Azure Resources
    runs-on: ubuntu-latest    
    outputs:
      azure-webapp-name: ${{ steps.deploy-bicep.outputs.appServiceAppName }}
      function-app-name: ${{ steps.deploy-bicep.outputs.functionAppName }}
    steps:                
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
        
    # Deployment of template    
    - name: Deploy BICEP Template
      id: deploy-bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./deploy/main.bicep  # Set this to the location of your template file
        parameters: 'environmentType=nonprod githubOrg="${{ secrets.HTB_GITHUB_ORG }}" githubProductHeaderValue="${{ secrets.HTB_GITHUB_PROD_HEAD_VAL }}" githubInstallationId="${{ secrets.HTB_GITHUB_INSTALL_ID }}" githubAppId="${{ secrets.HTB_GITHUB_APP_ID }}" githubPrivateKeyVal="${{ secrets.HTB_GITHUB_PRIV_KEY }}"'

  deploy_webapp:
    name: Deploy TeamBuilder.GitHub
    runs-on: ubuntu-latest
    needs: [build, provision]
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download API artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app
        path: ${{ github.workspace }}/webapp    

    - name: Download Serverless artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: func-app
        path: ${{ github.workspace }}/funcapp 

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.provision.outputs.azure-webapp-name }}
        package: ./webapp

    - name: 'Deploy to Function App'
      uses: Azure/functions-action@v1
      id: deploy-to-funcapp
      with:
        app-name: ${{ needs.provision.outputs.function-app-name }}
        package: ./funcapp

    - name: logout
      run: |
        az logout